package xyz.welab.iframe.pojo;

import java.util.Date;

public class Parent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent.parent_id
     *
     * @mbg.generated
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent.parent_name
     *
     * @mbg.generated
     */
    private String parentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent.parent_resgister
     *
     * @mbg.generated
     */
    private Date parentResgister;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent.parent_tel
     *
     * @mbg.generated
     */
    private Integer parentTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent.parent_audition_order
     *
     * @mbg.generated
     */
    private Date parentAuditionOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent.parent_audition_finish
     *
     * @mbg.generated
     */
    private Date parentAuditionFinish;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent.first_paid_date_time
     *
     * @mbg.generated
     */
    private Date firstPaidDateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent.parent_id
     *
     * @return the value of parent.parent_id
     *
     * @mbg.generated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent.parent_id
     *
     * @param parentId the value for parent.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent.parent_name
     *
     * @return the value of parent.parent_name
     *
     * @mbg.generated
     */
    public String getParentName() {
        return parentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent.parent_name
     *
     * @param parentName the value for parent.parent_name
     *
     * @mbg.generated
     */
    public void setParentName(String parentName) {
        this.parentName = parentName == null ? null : parentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent.parent_resgister
     *
     * @return the value of parent.parent_resgister
     *
     * @mbg.generated
     */
    public Date getParentResgister() {
        return parentResgister;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent.parent_resgister
     *
     * @param parentResgister the value for parent.parent_resgister
     *
     * @mbg.generated
     */
    public void setParentResgister(Date parentResgister) {
        this.parentResgister = parentResgister;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent.parent_tel
     *
     * @return the value of parent.parent_tel
     *
     * @mbg.generated
     */
    public Integer getParentTel() {
        return parentTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent.parent_tel
     *
     * @param parentTel the value for parent.parent_tel
     *
     * @mbg.generated
     */
    public void setParentTel(Integer parentTel) {
        this.parentTel = parentTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent.parent_audition_order
     *
     * @return the value of parent.parent_audition_order
     *
     * @mbg.generated
     */
    public Date getParentAuditionOrder() {
        return parentAuditionOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent.parent_audition_order
     *
     * @param parentAuditionOrder the value for parent.parent_audition_order
     *
     * @mbg.generated
     */
    public void setParentAuditionOrder(Date parentAuditionOrder) {
        this.parentAuditionOrder = parentAuditionOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent.parent_audition_finish
     *
     * @return the value of parent.parent_audition_finish
     *
     * @mbg.generated
     */
    public Date getParentAuditionFinish() {
        return parentAuditionFinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent.parent_audition_finish
     *
     * @param parentAuditionFinish the value for parent.parent_audition_finish
     *
     * @mbg.generated
     */
    public void setParentAuditionFinish(Date parentAuditionFinish) {
        this.parentAuditionFinish = parentAuditionFinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent.first_paid_date_time
     *
     * @return the value of parent.first_paid_date_time
     *
     * @mbg.generated
     */
    public Date getFirstPaidDateTime() {
        return firstPaidDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent.first_paid_date_time
     *
     * @param firstPaidDateTime the value for parent.first_paid_date_time
     *
     * @mbg.generated
     */
    public void setFirstPaidDateTime(Date firstPaidDateTime) {
        this.firstPaidDateTime = firstPaidDateTime;
    }
}