package xyz.welab.iframe.pojo;

import java.util.Date;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_id
     *
     * @mbg.generated
     */
    private Integer studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_name
     *
     * @mbg.generated
     */
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_age
     *
     * @mbg.generated
     */
    private String studentAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_sex
     *
     * @mbg.generated
     */
    private String studentSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_adress
     *
     * @mbg.generated
     */
    private String studentAdress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.first_paid_date_time
     *
     * @mbg.generated
     */
    private Date firstPaidDateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.first_course_date_time
     *
     * @mbg.generated
     */
    private Date firstCourseDateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.first_level
     *
     * @mbg.generated
     */
    private String firstLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.last_course_date_time
     *
     * @mbg.generated
     */
    private Date lastCourseDateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.last_level
     *
     * @mbg.generated
     */
    private String lastLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.life_cycle
     *
     * @mbg.generated
     */
    private String lifeCycle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_id
     *
     * @return the value of student.student_id
     *
     * @mbg.generated
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_id
     *
     * @param studentId the value for student.student_id
     *
     * @mbg.generated
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_name
     *
     * @return the value of student.student_name
     *
     * @mbg.generated
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_name
     *
     * @param studentName the value for student.student_name
     *
     * @mbg.generated
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_age
     *
     * @return the value of student.student_age
     *
     * @mbg.generated
     */
    public String getStudentAge() {
        return studentAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_age
     *
     * @param studentAge the value for student.student_age
     *
     * @mbg.generated
     */
    public void setStudentAge(String studentAge) {
        this.studentAge = studentAge == null ? null : studentAge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_sex
     *
     * @return the value of student.student_sex
     *
     * @mbg.generated
     */
    public String getStudentSex() {
        return studentSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_sex
     *
     * @param studentSex the value for student.student_sex
     *
     * @mbg.generated
     */
    public void setStudentSex(String studentSex) {
        this.studentSex = studentSex == null ? null : studentSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_adress
     *
     * @return the value of student.student_adress
     *
     * @mbg.generated
     */
    public String getStudentAdress() {
        return studentAdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_adress
     *
     * @param studentAdress the value for student.student_adress
     *
     * @mbg.generated
     */
    public void setStudentAdress(String studentAdress) {
        this.studentAdress = studentAdress == null ? null : studentAdress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.first_paid_date_time
     *
     * @return the value of student.first_paid_date_time
     *
     * @mbg.generated
     */
    public Date getFirstPaidDateTime() {
        return firstPaidDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.first_paid_date_time
     *
     * @param firstPaidDateTime the value for student.first_paid_date_time
     *
     * @mbg.generated
     */
    public void setFirstPaidDateTime(Date firstPaidDateTime) {
        this.firstPaidDateTime = firstPaidDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.first_course_date_time
     *
     * @return the value of student.first_course_date_time
     *
     * @mbg.generated
     */
    public Date getFirstCourseDateTime() {
        return firstCourseDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.first_course_date_time
     *
     * @param firstCourseDateTime the value for student.first_course_date_time
     *
     * @mbg.generated
     */
    public void setFirstCourseDateTime(Date firstCourseDateTime) {
        this.firstCourseDateTime = firstCourseDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.first_level
     *
     * @return the value of student.first_level
     *
     * @mbg.generated
     */
    public String getFirstLevel() {
        return firstLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.first_level
     *
     * @param firstLevel the value for student.first_level
     *
     * @mbg.generated
     */
    public void setFirstLevel(String firstLevel) {
        this.firstLevel = firstLevel == null ? null : firstLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.last_course_date_time
     *
     * @return the value of student.last_course_date_time
     *
     * @mbg.generated
     */
    public Date getLastCourseDateTime() {
        return lastCourseDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.last_course_date_time
     *
     * @param lastCourseDateTime the value for student.last_course_date_time
     *
     * @mbg.generated
     */
    public void setLastCourseDateTime(Date lastCourseDateTime) {
        this.lastCourseDateTime = lastCourseDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.last_level
     *
     * @return the value of student.last_level
     *
     * @mbg.generated
     */
    public String getLastLevel() {
        return lastLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.last_level
     *
     * @param lastLevel the value for student.last_level
     *
     * @mbg.generated
     */
    public void setLastLevel(String lastLevel) {
        this.lastLevel = lastLevel == null ? null : lastLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.life_cycle
     *
     * @return the value of student.life_cycle
     *
     * @mbg.generated
     */
    public String getLifeCycle() {
        return lifeCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.life_cycle
     *
     * @param lifeCycle the value for student.life_cycle
     *
     * @mbg.generated
     */
    public void setLifeCycle(String lifeCycle) {
        this.lifeCycle = lifeCycle == null ? null : lifeCycle.trim();
    }
}