package xyz.welab.iframe.model;

import org.apache.ibatis.annotations.Param;
import xyz.welab.iframe.pojo.MyJss;
import xyz.welab.iframe.pojo.ParentEvent;

import java.util.Date;
import java.util.List;

public interface ParentEventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parent_event
     *
     * @mbg.generated
     */
    int insert(ParentEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parent_event
     *
     * @mbg.generated
     */
    int insertSelective(ParentEvent record);


    List<MyJss> yuekecishu(@Param("start_date") Date start_date,@Param("end_date") Date end_date );

    List<MyJss> gaiyuecishu(@Param("start_date") Date start_date,@Param("end_date") Date end_date );

    List<MyJss> xufei(@Param("start_date") Date start_date,@Param("end_date") Date end_date );

    List<MyJss> tuifei(@Param("start_date") Date start_date,@Param("end_date") Date end_date );
}