package xyz.welab.iframe.model;

import org.apache.ibatis.annotations.Param;
import xyz.welab.iframe.pojo.MyJss;
import xyz.welab.iframe.pojo.Parent;

import java.util.Date;
import java.util.List;
import java.util.Map;

public interface ParentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parent
     *
     * @mbg.generated
     */
    int insert(Parent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parent
     *
     * @mbg.generated
     */
    int insertSelective(Parent record);

    List<MyJss> getNum(@Param("start_date") Date start_date,@Param("end_date") Date end_date );

    List<MyJss> yuyueshiting(@Param("start_date") Date start_date,@Param("end_date") Date end_date );

    List<MyJss> shitingwancheng(@Param("start_date") Date start_date,@Param("end_date") Date end_date );

    List<MyJss> shoucifufei(@Param("start_date") Date start_date,@Param("end_date") Date end_date );


}