package xyz.welab.iframe.model;

import org.apache.ibatis.annotations.Param;
import xyz.welab.iframe.pojo.MyJss;
import xyz.welab.iframe.pojo.MyLlt;
import xyz.welab.iframe.pojo.MyZt;
import xyz.welab.iframe.pojo.Student;

import java.util.Date;
import java.util.List;

public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer studentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated
     */
    int insertSelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated
     */
    Student selectByPrimaryKey(Integer studentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Student record);


    List<MyLlt> nianling(@Param("start_date") Date start_date, @Param("end_date") Date end_date );

    List<MyLlt> xingbie(@Param("start_date") Date start_date, @Param("end_date") Date end_date );

    List<MyLlt> diqu(@Param("start_date") Date start_date, @Param("end_date") Date end_date );

    List<MyZt> nianlingdengji(@Param("start_date") Date start_date, @Param("end_date") Date end_date );

    List<MyLlt> shangkeshijian(@Param("start_date") Date start_date, @Param("end_date") Date end_date );

}