package xyz.welab.iframe.model;

import org.apache.ibatis.annotations.Param;
import xyz.welab.iframe.pojo.MyJss;
import xyz.welab.iframe.pojo.StudentEvent;

import java.util.Date;
import java.util.List;

public interface StudentEventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_event
     *
     * @mbg.generated
     */
    int insert(StudentEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_event
     *
     * @mbg.generated
     */
    int insertSelective(StudentEvent record);


    List<MyJss> yuxikecheng(@Param("start_date") Date start_date, @Param("end_date") Date end_date );

    List<MyJss> kechengwancheng(@Param("start_date") Date start_date, @Param("end_date") Date end_date );

    List<MyJss> kechengfuxi(@Param("start_date") Date start_date, @Param("end_date") Date end_date );

    List<MyJss> wanchengzuoye(@Param("start_date") Date start_date, @Param("end_date") Date end_date );

    List<MyJss> shangkeshijian(@Param("start_date") Date start_date, @Param("end_date") Date end_date );

}